### ISSUE TITLE
PubNubException: 400 error: No UUID specified

### ISSUE THREAD

**Issue by YashSavsani** [pubnub/dart#109]
```
PubNubException: PubNubException: 400 error: No UUID specified
#0      new PubNubException (package:pubnub/src/core/exceptions.dart:9)
#1      getExceptionFromDefaultResult (package:pubnub/src/dx/_utils/exceptions.dart:44)
#2      getExceptionFromAny (package:pubnub/src/dx/_utils/exceptions.dart:7)
#3      _defaultFlow (package:pubnub/src/dx/_utils/default_flow.dart:97)
<asynchronous suspension>
#4      Fiber.run (package:pubnub/src/core/supervisor/fiber.dart:36)
<asynchronous suspension>
#5      defaultFlow (package:pubnub/src/dx/_utils/default_flow.dart:26)
<asynchronous suspension>
```
<img width="853" alt="Screenshot 2023-03-09 at 11 24 58 AM" src="https://user-images.githubusercontent.com/97099792/223932934-4e9a1976-db3c-4271-973f-2409e3100f42.png">

PubNub Version: ^4.2.1
Dart SDK version: 2.19.2 (stable)
Flutter version: 3.7.5 (stable)

**Comment by mohitpubnub** [comment]
Please make sure that `userId` at pubnub instance's keyset OR a `uuid` value at method parameter is provided.
When uuid is not provided at method level then it uses keyset's value.

**Comment by YashSavsani** [comment]
I am passing `userId` at pubnub instance's keyset.

**Comment by are** [comment]
Do you know which operation resulted in this error?

**Comment by YashSavsani** [comment]
No we don't know about that. Our error logging mechanism is not giving us that information.

**Comment by are** [comment]
Could you enable PubNub logging for this? Here is a guide on how to do that: https://www.pubnub.com/docs/sdks/dart/troubleshooting

**Comment by YashSavsani** [comment]
Sure, will do that.
